# Setup
title:               pj's blog
tagline:             'A personal blog'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://blog.pjnicolas.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Pedro Javier Nicolás
  url:               https://twitter.com/dizzyrobin
  email:             pedrojavier.nz@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: UA-175630424-1
